name: Production Deployment

on:
  push:
    tags:
      - production-*
    paths:
      - "terraform/**"
  workflow_dispatch:
    branches:
      - main

jobs:
  fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform_fmt
        id: fmt
        run: terraform -chdir=terraform fmt -check
        continue-on-error: false
